
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}  
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD} 
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data 
    networks:
      - minio_net
  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   networks:
  #     - minio_net
  #   environment:
  #     - MY_USER=${MINIO_USER}
  #     - MY_PASS=${MINIO_PASSWORD}
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       until mc alias set local http://minio:9000 ${MY_USER} ${MY_PASS}; do
  #         echo 'Esperando a MinIO...'
  #         sleep 1
  #       done
        
  #       mc mb local/componentes --ignore-existing
  #       mc anonymous set public local/componentes
        
  #       echo '¡Configuración completada!'
  #       exit 0

networks:
  minio_net:
    driver: bridge